import Home from "./Home/Home"
import Header from "./Header/Header";
import Carousel from './Carousel/Carousel'
import Card from "./GoodsCard/GoodsCard"
import GoodsList from "./GoodsList/GoodsList"
import Goods from './Goods/Goods'
import GoodsTab from './GoodsTab/GoodsTab'
import CategoriesList from './CategoriesList/CategoriesList'
import CategoryList from './CategoryList/CategoryList'
import CategoryCard from './CategoryCard/CategoryCard'
import Delivery from './Delivery/Delivery'
import Aboutus from './Aboutus/Aboutus'
import Orders from './Orders/Orders'
import OrderCard from './OrderCard/OrderCard'
import Order from './Order/Order'
import Likes from "./Likes/Likes";
import CategoryListCard from './CategoryListCard/CategoryListCard'
import Settings from './Settings/Settings'
export { Home, Header, Carousel, Card, GoodsList, Goods, GoodsTab, CategoriesList, CategoryList, CategoryCard, Delivery, Aboutus, Orders, OrderCard, Order,Likes,CategoryListCard,Settings }